server:
  port: 8082

spring:
  config:
    activate:
      on-profile: default
  application:
    name: vuelos
  datasource:
    url: jdbc:mysql://${vuelos-db:localhost}:3309/vuelos
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update