server:
  port: 8081

spring:
  config:
    activate:
      on-profile: default
  application:
    name: hoteles
  datasource:
    url: jdbc:mysql://${hoteles-db:localhost}:${production-port:3308}/hoteles
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
